[package]
name = "nvimsence-rs"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discord-rich-presence = "0.2.0"
neovim-lib = "0.6.1"
lazy_static = "1.4"
serde_json = "1.0"
regex = "1.5"
